# Generated by Django 3.1 on 2021-01-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
    ]
